apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: result
  name: result
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: result
    spec:
      containers:
      - args:
        - nodemon
        - --debug
        - server.js
        image: mayankt/mayanktahil-resume:master
        imagePullPolicy: Always
        name: result
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
